server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: order
  cloud:
    config:
      server:
        git:
          uri: https://github.com/guoyang123/respo-config.git
          username: xx@qq.com
          password: xx

logging:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.bus: debug
