server:
  port: 8088

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.94.155.74:3306/shopping?characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: Qinfo20180507@
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
  rabbitmq:
    host: 47.94.155.74
    port: 5672
    username: root
    password: Qinfo20180507      

mybatis:
  mapper-locations: classpath*:com/neuedu/mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml


user:
  username: root

upload:
  path: /imgs


redis:
  maxTotal: 8
  maxIdle: 8
  minIdle: 0
  blockWhenExhausted: true
  maxWaitMillis: 10000
  testOnBorrow: true
  testOnReturn: true
  jmxEnabled: true
  redisHost: 47.94.155.74
  redisPort: 6379
  redisPassword: Qinfo20180507
  timeout: 1000


alipay:
  callback:
    url: http://47.94.155.74:8888/order/alipay_callback.do
  qrcode:
    path: /imgs
  public:
    key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv13O9pnPMfcP9ZgjiPRjxIcEpd/dEXU0qZU3++jrd5ItZIhTvmH9PuIylN4jxeY4qcaf/OVaQ074qd2xl0LDEDh9TA8ZNBwXEVROkDAhOsi6V7emjRCJrlkY0a9XvmPjoxKZ3K2y/laxtktoSw1xY3sXQl9v/rQnlsqSds7Ye9mGLAOvNUAQ/zyaCckjdRYcL3OARaHF/05grc1Q4Y3RvP8MD9F11TuSYRtgi34/m1tVqESRr7OKt3TFL6Zt1bxtri26bc3dzWKIE7C41L2gKZApmNEDzQAzsMJx5hH7YfVUxTc1CgvfTXvYaob7j3hZp3fKan+wBsw9IX1MwxIxxwIDAQAB

token:
  timeout: 10

ftp:
  host: 47.94.155.74
  user: ftpuser
  pass: Qinfo20180507@
env:
  prod

bus: test13
